title: Elkhan Ismayilzada
position: Graduate Student
affiliation: Michigan State University
email: ismayil1 (at) msu.edu
keywords:
google_scholar: https://scholar.google.com/citations?user=eDlBK6MAAAAJ&hl=en
github_link: https://github.com/elkhanzada
linkedin: https://www.linkedin.com/in/elkhanzada
avatar: ./assets/img/my_pic.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/my_pic.jpg
favicon_dark: ./assets/img/my_pic.jpg
description: Elkhan Ismayilzada's homepage
remote_theme: yaoyao-liu/minimal-light
